name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Obrigado por abrir sua primeira issue! Logo damos uma olhada."
        pr-message: "Valeu pela sua primeira pull request! A gente vai revisar em breve."
