name: Validar HTML

on: [push, pull_request]

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validar HTML
        uses: svenstaro/html5validator-action@v0.4.0
        with:
          root: .
          blacklist: node_modules
